### ISSUE TITLE
Version Framagit inaccessible

### ISSUE THREAD

**Issue by TroniQ89** [FredBezies/arch-tuto-installation#1]
Salut.

Sur Framagit, la repo n'est pas accessible, il faut donner l'accès à l'onglet "Repository" dans les options de ta repo ;)

Je vais contribuer en faisant une adapt EN ;)

**Comment by FredBezies** [comment]
Normalement, j'ai corrigé cela. Tu me confirmes ?

**Comment by TroniQ89** [comment]
Tout est ok ! ;)

Merci !
