### ISSUE TITLE
Systemd-timesynd à la place de NTP

### ISSUE THREAD

**Issue by frederic2ec** [FredBezies/arch-tuto-installation#11]
Hello,
Dans ton tutoriel tu installe ntp (pour la synchro en réseau). Depuis un petit moment déja systemD a intégré une alternative qui est : systemd-timesyncd (https://wiki.archlinux.org/index.php/Systemd-timesyncd) et qui fait exactement la meme chose. Serait-il mieux de garder NTP ou de le remplacer par celui de systemd.

Merci encore pour le tuto.

**Comment by ghost** [comment]
Bonjour,

Petite remarque quand même. systemd-timesyncd n'est pas une alternative à NTP ou chronyd. Il fait du SNTP, et donc ne gère que la partie NTP client, pas la partie NTP serveur. Pas très gênant pour un usage personnel, mais à noter tout de même.

**Comment by frederic2ec** [comment]
Bonjour,
Certe mais sont tutoriel est orienter pour la bureautique d'où l'utilisation de systemd-timesyncd à la place de NTP, pas besoin de plus lorsque timesyncd fais déjà le boulo.

Merci.

**Comment by FredBezies** [comment]
Je laisse la question ouverte pour le moment.

**Comment by ghost** [comment]
Bonjour,

Je suis d'accord sur le principe avec toi frederic2ec. Mais l'intérêt d'un tuto, c'est aussi de faire monter les gens en compétences, et savoir installer et utiliser NTP, c'est quand même intéressant, étant donné qu'on le retrouve partout. Au moins savoir que ça existe.

Après bien sur, si on part du principe que le tuto doit juste permettre à quelqu'un d'installer Arch sans trop se poser de questions, systemd-timesyncd fait le travail.

**Comment by MatMoul** [comment]
Une installation nécessite avant tout un client ntp mais le paquet ntp est avant tout un serveur...
timedatectl fait le job sans paquets supplémentaires...
`nano /etc/systemd/timesyncd.conf`
`timedatectl set-ntp true`

**Comment by FredBezies** [comment]
Merci pour l'info. Je regarderai cela à tête reposée.

**Comment by Urgau** [comment]
@FredBezies Après quelque mois de réflexion, as-tu un avis sur systemd-timesynd ?

**Comment by FredBezies** [comment]
Aucun. J'avoue que je n'ai pas pensé à regarder cet outil. Mea culpa !

**Comment by FredBezies** [comment]
Étant donné que le tutoriel sera archivé au 15 août, je clos le bug.
