### ISSUE TITLE
Ajout de tlp pour les portables

### ISSUE THREAD

**Issue by seigneurfuo** [FredBezies/arch-tuto-installation#14]
Bonjour. Je pense que cela pourrait être un plus d'installer tlp pour les ordinateurs portables afin d'économiser la durée de vie de la batterie. Ou bien simplement ajouter un lien vers la page Wiki correspondante:
[https://wiki.archlinux.org/index.php/TLP](https://wiki.archlinux.org/index.php/TLP)

Cordialement.

**Comment by FredBezies** [comment]
Pas une mauvaise idée. Je la mets sur la liste des trucs à ajouter pour le tuto de juillet.

**Comment by FredBezies** [comment]
Fait ! https://github.com/FredBezies/arch-tuto-installation/commit/c95d95f7b1cb6d3fba7f437c72ee2d59817433c3
