### ISSUE TITLE
Grub

### ISSUE THREAD

**Issue by miradozk** [FredBezies/arch-tuto-installation#15]
Bonjour,
J'ai peut-être mal compris le fonctionnement mais après installation de grub, normalement la machine boot directement sur grub , n'est ce pas?

Pour ma part, je dois choisir de démarrer sur un fichier EFI manuellement pour avoir un grub. En plus os-prober n'a pas trouvé l'installation Windows. Je suis en dual boot avec Windows 10 sur un laptop HP Pavillion. Y-a-t-il une solution pour le faire démarrer directement sur grub?

Merci

**Comment by FredBezies** [comment]
Bonjour.

S'il demande de démarrer sur une fichier efi, c'est que celui-ci n'est pas détecté. Il faudrait voir l'ordre de démarrage dans l'interface de l'UEFI, non ?

Pour le moment, je ne vois pas d'autre possibilité. Mais il est vrai que le dualboot en UEFI n'est pas quelque chose que j'ai beaucoup pratiqué pour le moment.

**Comment by miradozk** [comment]
Re.
J'ai tout de suite regarder l'ordre mais ca m'a l'air bon.

**Comment by FredBezies** [comment]
D'accord. Je n'ai pas trop le temps en ce moment pour aller plus loin. Je vais réfléchir au problème à tête reposée.

Désolé pour l'allongement du délai pour dépanner le problème.

**Comment by ghost** [comment]
Bonjour,

J'ai déjà observé ce comportement sur certains UEFI (laptops HP il me semble).
Pour ne pas avoir à choisir le fichier EFI à chaque fois, il faut entrer dans le setup de l'UEFI, et enregister un nouveau chargeur de démarrage pointant vers ce fichier.

Je ne sais pas pourquoi ce n'est pas automatique sur certains UEFI... La magie d'une norme que chaque constructeur implémente à sa sauce.... Même problème que pour l'ACPI...

**Comment by miradozk** [comment]
Je viens de resoudre mon probleme en remplacant le fichier efi de Windows par celui d'archlinux (backup à faire avant ) .

S'il faut booter sur Windows, il suffit de modifier l'entrée grub de windows .
