### ISSUE TITLE
Disposition du clavier sous Archlinux32

### ISSUE THREAD

**Issue by shiioo** [FredBezies/arch-tuto-installation#18]
Je pensais faire un commentaire sur la page du blog, mais elle est maintenant verrouillée. Je laisse donc l'info ici, au cas où elle puisse servir à quelqu'un.

Après plusieurs essais sous VM, j'ai décidé de franchir le pas et de passer mon vieux portable d'une Debian vers une Archlinux.
La bestiole n'étant plus toute jeune, j'ai donc pris la dernière version 32bit disponible.

Il est à noter qu'avec cette version x86, il y a un souci concernant la mise en place du clavier FR.
En effet, comme mentionné ici : https://bbs.archlinux32.org/viewtopic.php?id=506 , il y a un petit bug (qui n'existe pas en x64) concernant les permissions et malgré un fichier de configuration valide, le système n'arrive pas à extraire le fichier dont on a besoin, forçant le système à démarrer en mode qwerty.

La solution, mentionnée sur ce même sujet, consiste à dézipper le fichier qui nous intéresse et le problème est corrigé. Pour une disposition "France", il faut donc rentrer cette commande supplémentaire :
`gunzip /usr/share/kbd/keymaps/i386/azerty/fr-latin9.map.gz`

Et le tour est joué =)

**Comment by FredBezies** [comment]
Désolé pour la réponse plus que tardive. J'ai vérifié récemment, et cette saloperie de bug est toujours en vie :(

**Comment by FredBezies** [comment]
Le tutoriel fermant au 15 août 2019, je clos le bug.
