### ISSUE TITLE
Question de licence

### ISSUE THREAD

**Issue by antonincms** [FredBezies/arch-tuto-installation#21]
Bonjour Frederic,

J'aime beaucoup ton travail avec ce tutoriel, et je me posais une petite question. Il y a beaucoup de modifications que j'aimerais parfois y faire, parfois simplement pour mon utilisation en tant que handbook, et pour cela je réfléchissait à faire un fork. Mais je me suis rendu compte que sur github, en tout cas, tu ne mentionne pas de licence (libre ou non d'ailleurs).
Sous quelle licence publies tu donc cette édition "github" de ton guide ?

**Comment by antonincms** [comment]
Mea culpa, je viens de voir sur ton blog que tu indiques la distribuer en CC-BY-SA.
Si tu gardes le CC-BY-SA utilisé pour les epub / mobi, tu devrais créer un fichier LICENSE à la racine, avec la bonne licence si elle est présente par défaut dans github (sinon, la version plaintext est ici : https://creativecommons.org/licenses/by-sa/4.0/legalcode.txt) ce serais plus rassurant quand on veut justement participer.

**Comment by FredBezies** [comment]
Ajout fait à l'instant. Merci pour le rappel :)
