### ISSUE TITLE
Swap SSD NVMe

### ISSUE THREAD

**Issue by XavierBeheydt** [FredBezies/arch-tuto-installation#24]
Bonjour, je suis le tutoriel pour l'installation, je dispose d'un Thinkpad avec un SSD NVMe. Ainsi, je n'arrive pas à avoir une information claire à propose du SWAP sur un disque SSD. Je vois des 
configurations avec discard ou TRIM.

As-tu des recommandations à propos de cela ?

Merci

**Comment by FredBezies** [comment]
Bonjour.

Mon tutoriel est une base autour de laquelle il faut s'adapter. Personnellement, j'éviterai le swap sur un SSD / NVMe.

Les recommandations par rapport au trim et au discard ? Le mieux est de jeter un oeil au wiki d'archlinux qui saura mieux répondre que moi ici.

**Comment by XavierBeheydt** [comment]
Merci pour ton retour, j'ai fait pas mal de recherche et j'ai trouvé pas mal d'informations. Je pense proposé des pistes sur cette issue si cela intéresse pour d'autres personnes.

Je les posterai une fois tester et vérifier avant de ferme l'issue.

Merci

**Comment by FredBezies** [comment]
Cela fait 6 mois que le bug n'a pas bougé. Je le clos.
