### ISSUE TITLE
trizen?

### ISSUE THREAD

**Issue by luclu7** [FredBezies/arch-tuto-installation#4]
Ça ne serait pas une meilleure idée d'utiliser trizen que yaourt ? Il est un peu plus rapide (et maintenu).

**Comment by FredBezies** [comment]
Bonjour.

Une idée à creuser. Cependant, je ne veux pas faire compiler un paquet dès le guide. Pour le moment, je met la suggestion de côté pour une version ultérieure du guide.

**Comment by micleb** [comment]
Bonjour, ça tombe bien que cette issue soit ouverte, j'avais justement une question en lien avec les AUR helpers.

Pourquoi avoir supprimé la section sur Yaourt dans le guide ?

**Comment by FredBezies** [comment]
Yaourt est un outil qui commence à prendre la poussière. D'ailleurs, même si Archlinux ne recommande l'utilisation d'aucun outil simplificateu, yaourt fait parti du pire au niveau des fonctionnalités recherchées.

https://wiki.archlinux.org/index.php/AUR_helpers

Je compte rajouter une section sur Trizen pour la version du mois d'août 2018.

**Comment by micleb** [comment]
D'accord, je viens d'installer Trizen, je vais tester ça. Merci bien :+1:

**Comment by FredBezies** [comment]
Rajouté :)

Cf https://github.com/FredBezies/arch-tuto-installation/commit/585ac5df3421acd07545a7ca782f4c34df2b5ad1
