### ISSUE TITLE
Autre system d'init

### ISSUE THREAD

**Issue by Erwan13430** [FredBezies/arch-tuto-installation#5]
Bonjour fredo. Serait-il possible que tu fasse un tuto pour installer Arch Linux avec un SysvInit plutot que systemd (je parle réellement de SysVinit et non pas de OpenRc)
Merci par avance de ta réponse.

Cordialement,

FallingKnife84

**Comment by FredBezies** [comment]
Bonjour.

Il est presque impossible d'avoir un ensemble sysvinit + scripts franchement fonctionnel sur AUR. Donc, je suis obligé de répondre par la négative à ta demande.

Cordialement,
