### ISSUE TITLE
Sommaire ?

### ISSUE THREAD

**Issue by raymater** [FredBezies/arch-tuto-installation#6]
Qu'est-ce que c'est bien ce tutoriel ! Dire que c'est galère en ligne de commandes parfois. Ça manque juste un petit sommaire au début du document histoire que ça rende encore mieux.

**Comment by FredBezies** [comment]
La mise en place est plus ennuyeuse que prévue. Je compte prévoir cela pour la version de juillet 2018.

**Comment by FredBezies** [comment]
Sommaire préliminaire rajouté grace à Kevin Dubrulle. Bug clos.
