### ISSUE TITLE
Partition EFI System : mkfs.fat Device busy

### ISSUE THREAD

**Issue by raymater** [FredBezies/arch-tuto-installation#7]
Une erreur de type "device busy" peut se produire lorsqu'on veut formater la partition EFI après l'avoir créé via cfdisk avec la commande mkfs.fat.

Pour résoudre cette erreur, un redémarrage de la machine est nécessaire après la création des partitions.

**Comment by FredBezies** [comment]
Normalement, tu dois utiliser cgdisk pour du gpt. C'est plus adapté.

**Comment by raymater** [comment]
D'accord, je tâcherai de m'en souvenir
