### ISSUE TITLE
Runit

### ISSUE THREAD

**Issue by Erwan13430** [FredBezies/arch-tuto-installation#9]
Bonjour Frédéric
Serait il possible que vous fassiez un Tito pour avoir runit sous arch depuis l'installation ou une vidéo pour nous expliquer comment migrer sous runit?

Cordialement,

F_K

**Comment by FredBezies** [comment]
@Fallingknife84 : je ne sais pas si les paquets pour runit serait facilement installable. Il faudrait que je me plonge dans le wiki pour en savoir plus. Je ne promets rien.

**Comment by FredBezies** [comment]
J'ai essayé récemment. Les paquets nécessaires sont soit morts, soit complètement obsolètes. Autant dire que c'est une tâche que je ne pourrais pas accomplir à court terme. Désolé.
